### ISSUE TITLE
Soy final build not working

### ISSUE THREAD

**Issue by jjoselv** [metal/metal-tutorial-todo#2]
### Description
Soy final build not working

#### Steps to Reproduce
`npm install`
`npm build:soy:final`

#### Expected Results
No errors on final compilation

#### Actual Results
```
$ npm run build:soy:final

> metal-tutorial-todo@ build:soy:final C:\Users\JuanjoLopez\workspace\appappapp
> npm run soy:final && webpack --config webpack.config.soy.js --entry ./src/soy/final/TodoApp.js


> metal-tutorial-todo@ soy:final C:\Users\JuanjoLopez\workspace\appappapp
> metalsoy -s src/soy/final/*.soy -d src/soy/final --soyDeps node_modules/metal*/src/**/*.soy node_modules/clay*/src/**/*.soy

Compiling soy
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metal-tutorial-todo@ soy:final: `metalsoy -s src/soy/final/*.soy -d src/soy/final --soyDeps node_modules/metal*/src/**/*.soy node_modules/clay*/src/**/*.soy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metal-tutorial-todo@ soy:final script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JuanjoLopez\AppData\Roaming\npm-cache\_logs\2018-03-09T13_06_44_950Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metal-tutorial-todo@ build:soy:final: `npm run soy:final && webpack --config webpack.config.soy.js --entry ./src/soy/final/TodoApp.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metal-tutorial-todo@ build:soy:final script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JuanjoLopez\AppData\Roaming\npm-cache\_logs\2018-03-09T13_06_44_982Z-debug.log
```

### Browsers Affected
None, error on build.

### Versions
The ones listed in the package.json for the tutorial:
https://github.com/metal/metal-tutorial-todo/blob/master/package.json

npm: 5.6.0
node.js: v8.10.0

**Comment by jjoselv** [comment]
Correctly working with npm -> 4.1.2 and nodejs -> v6.9.2 on a different computer (both using git bash on Windows x64)
